# Generated by Django 5.0.4 on 2026-04-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Store'), ('transit', 'Transit')], default='store', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('shelf', 'Shelf'), ('fridge', 'Fridge'), ('freezer', 'Freezer'), ('backroom', 'Backroom')], default='shelf', max_length=20)),
            ],
            options={
                'db_table': 'zones',
            },
        ),
    ]
